// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddClient(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function AddSection(arg1:string,arg2:string):Promise<string>;

export function AddTaxYear(arg1:string,arg2:string):Promise<string>;

export function ArchiveClient(arg1:string):Promise<string>;

export function AssignClientToFirmCalendar2026(arg1:string,arg2:string):Promise<Array<main.FirmCalendarAssignment>>;

export function AssignClientToFirmCalendarForPreparer2026(arg1:string,arg2:string,arg3:string):Promise<Array<main.FirmCalendarAssignment>>;

export function BackupClient(arg1:string):Promise<string>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ChooseEngagementLetterLogo():Promise<main.EngagementLetterLogoInfo>;

export function ChooseEngagementLetterOutput(arg1:string):Promise<string>;

export function ChooseEngagementLetterSavePath(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ChooseInvoiceSavePath(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearEngagementLetterLogo():Promise<void>;

export function CreateUserUnderExistingCompany(arg1:main.ExistingCompanyUserRegistration):Promise<main.UserProfile>;

export function CurrentUser():Promise<main.UserProfile>;

export function DataRoot():Promise<string>;

export function DeleteClient(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteSection(arg1:string):Promise<void>;

export function DeleteTaxYear(arg1:string):Promise<void>;

export function EngagementLetterDefaultOutput(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EnrollExistingUser(arg1:string,arg2:string):Promise<void>;

export function ExitBabyFileCab():Promise<void>;

export function GenerateEngagementLetter(arg1:main.EngagementLetterRequest,arg2:string):Promise<Array<string>>;

export function GenerateInvoice(arg1:main.InvoiceRequest,arg2:string):Promise<Array<string>>;

export function GetAppAuditTrail():Promise<Array<main.AppAuditEntry>>;

export function GetAuditTrail(arg1:string):Promise<Array<main.AuditEntry>>;

export function GetAutoLockMinutes():Promise<number>;

export function GetClientCommunications():Promise<Array<main.ClientCommunication>>;

export function GetClientProperties(arg1:string):Promise<main.ClientProperties>;

export function GetDocumentProperties(arg1:string):Promise<main.DocumentProperties>;

export function GetEngagementLetterLogo():Promise<main.EngagementLetterLogoInfo>;

export function GetFirmCalendar2026():Promise<Array<main.FirmCalendarAssignment>>;

export function GetNotes(arg1:string):Promise<string>;

export function GetNotesDocument(arg1:string):Promise<main.NotesDocument>;

export function GetPreview(arg1:string):Promise<main.Preview>;

export function GetTree():Promise<Array<main.TreeNode>>;

export function GlobalFind(arg1:string):Promise<Array<main.GlobalSearchResult>>;

export function HasUsers():Promise<boolean>;

export function ImportDroppedFiles(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ListArchivedClients():Promise<Array<main.TreeNode>>;

export function ListCompanies():Promise<Array<main.CompanyProfile>>;

export function ListCompanyUsers():Promise<Array<main.UserProfile>>;

export function LogAppEvent(arg1:string,arg2:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<main.UserProfile>;

export function Logout():Promise<void>;

export function MoveDocument(arg1:string,arg2:string):Promise<string>;

export function NodeType(arg1:string):Promise<string>;

export function OpenDataFolder():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenIRSCurrencyExchangeRatesPage():Promise<void>;

export function OpenIRSPaymentPage():Promise<void>;

export function ReassignClientInFirmCalendar2026(arg1:string,arg2:string,arg3:string):Promise<Array<main.FirmCalendarAssignment>>;

export function ReassignFirmCalendarPreparer2026(arg1:string,arg2:string,arg3:string):Promise<Array<main.FirmCalendarAssignment>>;

export function RegisterUser(arg1:main.UserRegistration):Promise<main.UserProfile>;

export function RemoveClientFromFirmCalendar2026(arg1:string,arg2:string):Promise<Array<main.FirmCalendarAssignment>>;

export function RenameClient(arg1:string,arg2:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function RenameSection(arg1:string,arg2:string):Promise<string>;

export function RenameTaxYear(arg1:string,arg2:string):Promise<string>;

export function RenderPDFPage(arg1:string,arg2:number):Promise<string>;

export function RestoreClient(arg1:string):Promise<string>;

export function SaveDocumentDescription(arg1:string,arg2:string):Promise<void>;

export function SaveNotes(arg1:string,arg2:string):Promise<void>;

export function SaveNotesDocument(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchPDF(arg1:string,arg2:string):Promise<main.PDFSearchResponse>;

export function SessionActive():Promise<boolean>;

export function SetAutoLockMinutes(arg1:number):Promise<void>;

export function SetFirmCalendarStatus2026(arg1:string,arg2:string,arg3:string):Promise<Array<main.FirmCalendarAssignment>>;

export function TouchActivity():Promise<boolean>;

export function UnarchiveClient(arg1:string):Promise<string>;

export function UpdateClientProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UploadFiles(arg1:string):Promise<Array<string>>;
