// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClient(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddClient'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddSection(arg1, arg2) {
  return window['go']['main']['App']['AddSection'](arg1, arg2);
}

export function AddTaxYear(arg1, arg2) {
  return window['go']['main']['App']['AddTaxYear'](arg1, arg2);
}

export function ArchiveClient(arg1) {
  return window['go']['main']['App']['ArchiveClient'](arg1);
}

export function AssignClientToFirmCalendar2026(arg1, arg2) {
  return window['go']['main']['App']['AssignClientToFirmCalendar2026'](arg1, arg2);
}

export function AssignClientToFirmCalendarForPreparer2026(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssignClientToFirmCalendarForPreparer2026'](arg1, arg2, arg3);
}

export function BackupClient(arg1) {
  return window['go']['main']['App']['BackupClient'](arg1);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function ChooseEngagementLetterLogo() {
  return window['go']['main']['App']['ChooseEngagementLetterLogo']();
}

export function ChooseEngagementLetterOutput(arg1) {
  return window['go']['main']['App']['ChooseEngagementLetterOutput'](arg1);
}

export function ChooseEngagementLetterSavePath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChooseEngagementLetterSavePath'](arg1, arg2, arg3, arg4);
}

export function ChooseInvoiceSavePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChooseInvoiceSavePath'](arg1, arg2, arg3);
}

export function ClearEngagementLetterLogo() {
  return window['go']['main']['App']['ClearEngagementLetterLogo']();
}

export function CreateUserUnderExistingCompany(arg1) {
  return window['go']['main']['App']['CreateUserUnderExistingCompany'](arg1);
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function DataRoot() {
  return window['go']['main']['App']['DataRoot']();
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteSection(arg1) {
  return window['go']['main']['App']['DeleteSection'](arg1);
}

export function DeleteTaxYear(arg1) {
  return window['go']['main']['App']['DeleteTaxYear'](arg1);
}

export function EngagementLetterDefaultOutput(arg1, arg2, arg3) {
  return window['go']['main']['App']['EngagementLetterDefaultOutput'](arg1, arg2, arg3);
}

export function EnrollExistingUser(arg1, arg2) {
  return window['go']['main']['App']['EnrollExistingUser'](arg1, arg2);
}

export function ExitBabyFileCab() {
  return window['go']['main']['App']['ExitBabyFileCab']();
}

export function GenerateEngagementLetter(arg1, arg2) {
  return window['go']['main']['App']['GenerateEngagementLetter'](arg1, arg2);
}

export function GenerateInvoice(arg1, arg2) {
  return window['go']['main']['App']['GenerateInvoice'](arg1, arg2);
}

export function GetAppAuditTrail() {
  return window['go']['main']['App']['GetAppAuditTrail']();
}

export function GetAuditTrail(arg1) {
  return window['go']['main']['App']['GetAuditTrail'](arg1);
}

export function GetAutoLockMinutes() {
  return window['go']['main']['App']['GetAutoLockMinutes']();
}

export function GetClientCommunications() {
  return window['go']['main']['App']['GetClientCommunications']();
}

export function GetClientProperties(arg1) {
  return window['go']['main']['App']['GetClientProperties'](arg1);
}

export function GetDocumentProperties(arg1) {
  return window['go']['main']['App']['GetDocumentProperties'](arg1);
}

export function GetEngagementLetterLogo() {
  return window['go']['main']['App']['GetEngagementLetterLogo']();
}

export function GetFirmCalendar2026() {
  return window['go']['main']['App']['GetFirmCalendar2026']();
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetNotesDocument(arg1) {
  return window['go']['main']['App']['GetNotesDocument'](arg1);
}

export function GetPreview(arg1) {
  return window['go']['main']['App']['GetPreview'](arg1);
}

export function GetTree() {
  return window['go']['main']['App']['GetTree']();
}

export function GlobalFind(arg1) {
  return window['go']['main']['App']['GlobalFind'](arg1);
}

export function HasUsers() {
  return window['go']['main']['App']['HasUsers']();
}

export function ImportDroppedFiles(arg1, arg2) {
  return window['go']['main']['App']['ImportDroppedFiles'](arg1, arg2);
}

export function ListArchivedClients() {
  return window['go']['main']['App']['ListArchivedClients']();
}

export function ListCompanies() {
  return window['go']['main']['App']['ListCompanies']();
}

export function ListCompanyUsers() {
  return window['go']['main']['App']['ListCompanyUsers']();
}

export function LogAppEvent(arg1, arg2) {
  return window['go']['main']['App']['LogAppEvent'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MoveDocument(arg1, arg2) {
  return window['go']['main']['App']['MoveDocument'](arg1, arg2);
}

export function NodeType(arg1) {
  return window['go']['main']['App']['NodeType'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenIRSCurrencyExchangeRatesPage() {
  return window['go']['main']['App']['OpenIRSCurrencyExchangeRatesPage']();
}

export function OpenIRSPaymentPage() {
  return window['go']['main']['App']['OpenIRSPaymentPage']();
}

export function ReassignClientInFirmCalendar2026(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReassignClientInFirmCalendar2026'](arg1, arg2, arg3);
}

export function ReassignFirmCalendarPreparer2026(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReassignFirmCalendarPreparer2026'](arg1, arg2, arg3);
}

export function RegisterUser(arg1) {
  return window['go']['main']['App']['RegisterUser'](arg1);
}

export function RemoveClientFromFirmCalendar2026(arg1, arg2) {
  return window['go']['main']['App']['RemoveClientFromFirmCalendar2026'](arg1, arg2);
}

export function RenameClient(arg1, arg2) {
  return window['go']['main']['App']['RenameClient'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameSection(arg1, arg2) {
  return window['go']['main']['App']['RenameSection'](arg1, arg2);
}

export function RenameTaxYear(arg1, arg2) {
  return window['go']['main']['App']['RenameTaxYear'](arg1, arg2);
}

export function RenderPDFPage(arg1, arg2) {
  return window['go']['main']['App']['RenderPDFPage'](arg1, arg2);
}

export function RestoreClient(arg1) {
  return window['go']['main']['App']['RestoreClient'](arg1);
}

export function SaveDocumentDescription(arg1, arg2) {
  return window['go']['main']['App']['SaveDocumentDescription'](arg1, arg2);
}

export function SaveNotes(arg1, arg2) {
  return window['go']['main']['App']['SaveNotes'](arg1, arg2);
}

export function SaveNotesDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNotesDocument'](arg1, arg2, arg3);
}

export function SearchPDF(arg1, arg2) {
  return window['go']['main']['App']['SearchPDF'](arg1, arg2);
}

export function SessionActive() {
  return window['go']['main']['App']['SessionActive']();
}

export function SetAutoLockMinutes(arg1) {
  return window['go']['main']['App']['SetAutoLockMinutes'](arg1);
}

export function SetFirmCalendarStatus2026(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFirmCalendarStatus2026'](arg1, arg2, arg3);
}

export function TouchActivity() {
  return window['go']['main']['App']['TouchActivity']();
}

export function UnarchiveClient(arg1) {
  return window['go']['main']['App']['UnarchiveClient'](arg1);
}

export function UpdateClientProfile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateClientProfile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadFiles(arg1) {
  return window['go']['main']['App']['UploadFiles'](arg1);
}
