const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../dist/app.js'),'utf8');
const chunk=source.slice(0,source.indexOf('async function runMappedShortcut'));
const records=new Map();const box={structuredClone,currentUser:{companyId:'a',username:'Alice'},localStorage:{getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v)},toast(){},document:{querySelector:()=>null},$:()=>null};
vm.createContext(box);vm.runInContext(chunk,box);
const defaults=box.defaultShortcutBindings();box.validateShortcutBindings(defaults);
assert.equal(box.shortcutFromEvent({key:'f',ctrlKey:true,shiftKey:true}),'Ctrl+Shift+F');
assert.equal(box.shortcutFromEvent({key:'b',metaKey:true}),'Ctrl+B');
assert.equal(box.shortcutFromEvent({key:'Shift'}),'');
assert.equal(box.shortcutFromEvent({key:'f',isComposing:true}),'');
const custom=box.defaultShortcutBindings();custom.upload=['Ctrl+Alt+U'];box.validateShortcutBindings(custom);
custom['add-client']=['Ctrl+Alt+U'];assert.throws(()=>box.validateShortcutBindings(custom),/already assigned/);
custom['add-client']=[];custom.upload=['Ctrl+S'];assert.throws(()=>box.validateShortcutBindings(custom),/reserved/);
custom.upload=['G'];assert.throws(()=>box.validateShortcutBindings(custom),/reserved/);
custom.upload=['Alt+F4'];assert.throws(()=>box.validateShortcutBindings(custom),/reserved/);
custom.upload=['Ctrl+Alt+U'];box.validateShortcutBindings(custom);
records.set(box.shortcutStorageKey(),JSON.stringify(custom));box.loadShortcutBindings();
assert.equal(vm.runInContext("shortcutBindings.upload[0]",box),'Ctrl+Alt+U');
box.currentUser.username='Bob';box.loadShortcutBindings();assert.equal(vm.runInContext('shortcutBindings.upload[0]',box),'F');
box.currentUser.username='Alice';box.currentUser.companyId='b';box.loadShortcutBindings();assert.equal(vm.runInContext('shortcutBindings.upload[0]',box),'F');
records.set(box.shortcutStorageKey(),'broken');box.loadShortcutBindings();assert.equal(vm.runInContext('shortcutBindings.upload[0]',box),'F');
console.log('PASS: normalization, conflicts, reserved keys, disabled actions, persistence and account separation');

assert.equal(box.shortcutFromEvent({key:'1',code:'Numpad1'}),'Numpad1');
assert.equal(box.shortcutFromEvent({key:'!',code:'Digit1',shiftKey:true}),'Shift+1');
assert.equal(box.shortcutFromEvent({key:'Enter',code:'NumpadEnter',ctrlKey:true}),'Ctrl+NumpadEnter');
assert.equal(box.shortcutFromEvent({key:'ArrowLeft'}),'ArrowLeft');
assert.equal(box.shortcutAllowed('Alt+Shift+NumpadAdd'),true);
assert.equal(box.shortcutAllowed('Ctrl+F24'),true);
assert.equal(box.shortcutAllowed('Shift+Ctrl+A'),false);
assert.equal(box.shortcutAllowed('Numpad99'),false);
const nodes={};
for(const id of ['shortcutEditCtrl','shortcutEditAlt','shortcutEditShift','shortcutEditKey','shortcutEditError','shortcutEditBackdrop','shortcutMapperSave'])nodes[id]={checked:false,value:'',textContent:'',classList:{add(){}},focus(){}};
box.$=id=>nodes[id]; box.renderShortcutMapper=()=>{};
vm.runInContext("shortcutDraft=defaultShortcutBindings(); shortcutEditingRow={id:'rename-file',index:1};",box);
nodes.shortcutEditCtrl.checked=true;nodes.shortcutEditKey.value='Numpad7';box.applyShortcutEditor();
assert.equal(vm.runInContext('shortcutDraft["rename-file"][0]',box),'F2');
assert.equal(vm.runInContext('shortcutDraft["rename-file"][1]',box),'Ctrl+Numpad7');
vm.runInContext("shortcutEditingRow={id:'rename-file',index:1}",box);
nodes.shortcutEditKey.value='B';box.applyShortcutEditor();
assert.match(nodes.shortcutEditError.textContent,/already assigned/);
assert.equal(vm.runInContext('shortcutDraft["rename-file"][1]',box),'Ctrl+Numpad7');
