const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../dist/app.js'), 'utf8');
const chunk = source.slice(source.indexOf('function fileSelectionRange('), source.indexOf('async function selectNode('));
const row = (filePath, open = true) => ({dataset: {path: filePath}, parentElement: {tagName: 'DETAILS', open, parentElement: null}});
const rows = [row('/client/a'), row('/client/hidden', false), row('/client/b'), row('/client/c'), row('/other/d')];
const sandbox = {treeData: [{path: '/client'}, {path: '/other'}], $: () => ({querySelectorAll: () => rows})};
vm.createContext(sandbox);
vm.runInContext(chunk, sandbox);
const range = (...args) => Array.from(sandbox.fileSelectionRange(...args));
assert.deepEqual(range(['a','b','c','d'], 'a', 'c'), ['a','b','c']);
assert.deepEqual(range(['a','b','c','d'], 'd', 'b'), ['b','c','d']);
assert.deepEqual(range(['a','b'], 'missing', 'b'), ['b']);
const visible = Array.from(sandbox.visibleClientFilePaths({path:'/client/c'}));
assert.deepEqual(visible, ['/client/a','/client/b','/client/c']);
assert.deepEqual(range(visible, '/other/d', '/client/c'), ['/client/c']);
console.log('PASS: forward/reverse ranges, hidden files excluded, client boundaries preserved');
